export type DomainErrorCode =
  | 'INVALID_AMOUNT'
  | 'AMOUNT_OVERFLOW'
  | 'INVALID_ACCOUNT_ID'
  | 'INVALID_TX_ID'
  | 'INVALID_IDEMPOTENCY_KEY'
  | 'ACCOUNT_NOT_FOUND'
  | 'ACCOUNT_NOT_ACTIVE'
  | 'INSUFFICIENT_BALANCE'
  | 'DUPLICATE_TRANSACTION'
  | 'CHECKPOINT_ALREADY_EXISTS';
